version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: fitbuddy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fitbud
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: fitbuddy-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  affiliate:
    image: postgres:14
    container_name: affiliate-mgt-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: fitbud
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: affiliate-mgt
    volumes:
      - affiliate-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  affiliate-data:
